export default [
  { country: "Afghanistan", countryCode: "AF", code: "+93" },
  { country: "Albania", countryCode: "AL", code: "+355" },
  { country: "Algeria", countryCode: "DZ", code: "+213" },
  { country: "Andorra", countryCode: "AD", code: "+376" },
  { country: "Angola", countryCode: "AO", code: "+244" },
  { country: "Antigua and Barbuda", countryCode: "AG", code: "+1-268" },
  { country: "Argentina", countryCode: "AR", code: "+54" },
  { country: "Armenia", countryCode: "AM", code: "+374" },
  { country: "Australia", countryCode: "AU", code: "+61" },
  { country: "Austria", countryCode: "AT", code: "+43" },
  { country: "Azerbaijan", countryCode: "AZ", code: "+994" },
  { country: "Bahamas", countryCode: "BS", code: "+1-242" },
  { country: "Bahrain", countryCode: "BH", code: "+973" },
  { country: "Bangladesh", countryCode: "BD", code: "+880" },
  { country: "Barbados", countryCode: "BB", code: "+1-246" },
  { country: "Belarus", countryCode: "BY", code: "+375" },
  { country: "Belgium", countryCode: "BE", code: "+32" },
  { country: "Belize", countryCode: "BZ", code: "+501" },
  { country: "Benin", countryCode: "BJ", code: "+229" },
  { country: "Bhutan", countryCode: "BT", code: "+975" },
  { country: "Bolivia", countryCode: "BO", code: "+591" },
  { country: "Bosnia and Herzegovina", countryCode: "BA", code: "+387" },
  { country: "Botswana", countryCode: "BW", code: "+267" },
  { country: "Brazil", countryCode: "BR", code: "+55" },
  { country: "Brunei", countryCode: "BN", code: "+673" },
  { country: "Bulgaria", countryCode: "BG", code: "+359" },
  { country: "Burkina Faso", countryCode: "BF", code: "+226" },
  { country: "Burundi", countryCode: "BI", code: "+257" },
  { country: "Cabo Verde", countryCode: "CV", code: "+238" },
  { country: "Cambodia", countryCode: "KH", code: "+855" },
  { country: "Cameroon", countryCode: "CM", code: "+237" },
  { country: "Canada", countryCode: "CA", code: "+1" },
  { country: "Central African Republic", countryCode: "CF", code: "+236" },
  { country: "Chad", countryCode: "TD", code: "+235" },
  { country: "Chile", countryCode: "CL", code: "+56" },
  { country: "China", countryCode: "CN",   code: "+86" },
  { country: "Colombia", countryCode: "CO", code: "+57" },
  { country: "Comoros", countryCode: "KM", code: "+269" },
  { country: "Congo", countryCode: "CG", code: "+242" },
  { country: "Congo, Democratic Republic", countryCode: "CD", code: "+243" },
  { country: "Costa Rica", countryCode: "CR", code: "+506" },
  { country: "Croatia", countryCode: "HR", code: "+385" },
  { country: "Cuba", countryCode: "CU", code: "+53" },
  { country: "Cyprus", countryCode: "CY", code: "+357" },
  { country: "Czech Republic", countryCode: "CZ", code: "+420" },
  { country: "Denmark", countryCode: "DK", code: "+45" },
  { country: "Djibouti", countryCode: "DJ", code: "+253" },
  { country: "Dominica", countryCode: "DM", code: "+1-767" },
  { country: "Dominican Republic", countryCode: "DO", code: "+1-809" },
  { country: "Dominican Republic", countryCode: "DO", code: "+1-829" },
  { country: "Dominican Republic", countryCode: "DO", code: "+1-849" },
  { country: "Ecuador", countryCode: "EC", code: "+593" },
  { country: "Egypt", countryCode: "EG", code: "+20" },
  { country: "El Salvador", countryCode: "SV", code: "+503" },
  { country: "Equatorial Guinea", countryCode: "GQ", code: "+240" },
  { country: "Eritrea", countryCode: "ER", code: "+291" },
  { country: "Estonia", countryCode: "EE", code: "+372" },
  { country: "Eswatini (Swaziland)", countryCode: "SZ", code: "+268" },
  { country: "Ethiopia", countryCode: "ET", code: "+251" },
  { country: "Fiji", countryCode: "FJ", code: "+679" },
  { country: "Finland", countryCode: "FI", code: "+358" },
  { country: "France", countryCode: "FR", code: "+33" },
  { country: "Gabon", countryCode: "GA", code: "+241" },
  { country: "Gambia", countryCode: "GM", code: "+220" },
  { country: "Georgia", countryCode: "GE", code: "+995" },
  { country: "Germany", countryCode: "DE", code: "+49" },
  { country: "Ghana", countryCode: "GH", code: "+233" },
  { country: "Greece", countryCode: "GR", code: "+30" },
  { country: "Grenada", countryCode: "GD", code: "+1-473" },
  { country: "Guatemala", countryCode: "GT", code: "+502" },
  { country: "Guinea", countryCode: "GN", code: "+224" },
  { country: "Guinea-Bissau", countryCode: "GW", code: "+245" },
  { country: "Guyana", countryCode: "GY", code: "+592" },
  { country: "Haiti", countryCode: "HT", code: "+509" },
  { country: "Honduras", countryCode: "HN", code: "+504" },
  { country: "Hungary", countryCode: "HU", code: "+36" },
  { country: "Iceland", countryCode: "IS", code: "+354" },
  { country: "India", countryCode: "IN", code: "+91" },
  { country: "Indonesia", countryCode: "ID", code: "+62" },
  { country: "Iran", countryCode: "IR", code: "+98" },
  { country: "Iraq", countryCode: "IQ", code: "+964" },
  { country: "Ireland", countryCode: "IE", code: "+353" },
  { country: "Israel", countryCode: "IL", code: "+972" },
  { country: "Italy", countryCode: "IT", code: "+39" },
  { country: "Jamaica", countryCode: "JM", code: "+1-876" },
  { country: "Japan", countryCode: "JP", code: "+81" },
  { country: "Jordan", countryCode: "JO", code: "+962" },
  { country: "Kazakhstan", countryCode: "KZ", code: "+7" },
  { country: "Kenya", countryCode: "KE", code: "+254" },
  { country: "Kiribati", countryCode: "KI", code: "+686" },
  { country: "Korea, North", countryCode: "KP", code: "+850" },
  { country: "Korea, South", countryCode: "KR", code: "+82" },
  { country: "Kosovo", countryCode: "XK", code: "+383" },
  { country: "Kuwait", countryCode: "KW", code: "+965" },
  { country: "Kyrgyzstan", countryCode: "KG", code: "+996" },
  { country: "Laos", countryCode: "LA", code: "+856" },
  { country: "Latvia", countryCode: "LV", code: "+371" },
  { country: "Lebanon", countryCode: "LB", code: "+961" },
  { country: "Lesotho", countryCode: "LS", code: "+266" },
  { country: "Liberia", countryCode: "LR", code: "+231" },
  { country: "Libya", countryCode: "LY", code: "+218" },
  { country: "Liechtenstein", countryCode: "LI", code: "+423" },
  { country: "Lithuania", countryCode: "LT", code: "+370" },
  { country: "Luxembourg", countryCode: "LU", code: "+352" },
  { country: "Madagascar", countryCode: "MG", code: "+261" },
  { country: "Malawi", countryCode: "MW", code: "+265" },
  { country: "Malaysia", countryCode: "MY", code: "+60" },
  { country: "Maldives", countryCode: "MV", code: "+960" },
  { country: "Mali", countryCode: "ML", code: "+223" },
  { country: "Malta", countryCode: "MT", code: "+356" },
  { country: "Marshall Islands", countryCode: "MH", code: "+692" },
  { country: "Mauritania", countryCode: "MR", code: "+222" },
  { country: "Mauritius", countryCode: "MU", code: "+230" },
  { country: "Mexico", countryCode: "MX", code: "+52" },
  { country: "Micronesia", countryCode: "FM", code: "+691" },
  { country: "Moldova", countryCode: "MD", code: "+373" },
  { country: "Monaco", countryCode: "MC", code: "+377" },
  { country: "Mongolia", countryCode: "MN", code: "+976" },
  { country: "Montenegro", countryCode: "ME", code: "+382" },
  { country: "Morocco", countryCode: "MA", code: "+212" },
  { country: "Mozambique", countryCode: "MZ", code: "+258" },
  { country: "Myanmar", countryCode: "MM", code: "+95" },
  { country: "Namibia", countryCode: "NA", code: "+264" },
  { country: "Nauru", countryCode: "NR", code: "+674" },
  { country: "Nepal", countryCode: "NP", code: "+977" },
  { country: "Netherlands", countryCode: "NL", code: "+31" },
  { country: "New Zealand", countryCode: "NZ", code: "+64" },
  { country: "Nicaragua", countryCode: "NI", code: "+505" },
  { country: "Niger", countryCode: "NE", code: "+227" },
  { country: "Nigeria", countryCode: "NG", code: "+234" },
  { country: "North Macedonia", countryCode: "MK", code: "+389" },
  { country: "Norway", countryCode: "NO", code: "+47" },
  { country: "Oman", countryCode: "OM", code: "+968" },
  { country: "Pakistan", countryCode: "PK", code: "+92" },
  { country: "Palau", countryCode: "PW", code: "+680" },
  { country: "Panama", countryCode: "PA", code: "+507" },
  { country: "Papua New Guinea", countryCode: "PG", code: "+675" },
  { country: "Paraguay", countryCode: "PY", code: "+595" },
  { country: "Peru", countryCode: "PE", code: "+51" },
  { country: "Philippines", countryCode: "PH", code: "+63" },
  { country: "Poland", countryCode: "PL", code: "+48" },
  { country: "Portugal", countryCode: "PT", code: "+351" },
  { country: "Qatar", countryCode: "QA", code: "+974" },
  { country: "Romania", countryCode: "RO", code: "+40" },
  { country: "Russia", countryCode: "RU", code: "+7" },
  { country: "Rwanda", countryCode: "RW", code: "+250" },
  { country: "Saint Kitts and Nevis", countryCode: "KN", code: "+1-869" },
  { country: "Saint Lucia", countryCode: "LC", code: "+1-758" },
  { country: "Saint Vincent and the Grenadines", countryCode: "VC", code: "+1-784" },
  { country: "Samoa", countryCode: "WS", code: "+685" },
  { country: "San Marino", countryCode: "SM", code: "+378" },
  { country: "Sao Tome and Principe", countryCode: "ST", code: "+239" },
  { country: "Saudi Arabia", countryCode: "SA", code: "+966" },
  { country: "Senegal", countryCode: "SN", code: "+221" },
  { country: "Serbia", countryCode: "RS", code: "+381" },
  { country: "Seychelles", countryCode: "SC", code: "+248" },
  { country: "Sierra Leone", countryCode: "SL", code: "+232" },
  { country: "Singapore", countryCode: "SG", code: "+65" },
  { country: "Slovakia", countryCode: "SK", code: "+421" },
  { country: "Slovenia", countryCode: "SI", code: "+386" },
  { country: "Solomon Islands", countryCode: "SB", code: "+677" },
  { country: "Somalia", countryCode: "SO", code: "+252" },
  { country: "South Africa", countryCode: "ZA", code: "+27" },
  { country: "South Sudan", countryCode: "SS", code: "+211" },
  { country: "Spain", countryCode: "ES", code: "+34" },
  { country: "Sri Lanka", countryCode: "LK", code: "+94" },
  { country: "Sudan", countryCode: "SD", code: "+249" },
  { country: "Suriname", countryCode: "SR", code: "+597" },
  { country: "Sweden", countryCode: "SE", code: "+46" },
  { country: "Switzerland", countryCode: "CH", code: "+41" },
  { country: "Syria", countryCode: "SY", code: "+963" },
  { country: "Taiwan", countryCode: "TW", code: "+886" },
  { country: "Tajikistan", countryCode: "TJ", code: "+992" },
  { country: "Tanzania", countryCode: "TZ", code: "+255" },
  { country: "Thailand", countryCode: "TH", code: "+66" },
  { country: "Timor-Leste", countryCode: "TL", code: "+670" },
  { country: "Togo", countryCode: "TG", code: "+228" },
  { country: "Tonga", countryCode: "TO", code: "+676" },
  { country: "Trinidad and Tobago", countryCode: "TT", code: "+1-868" },
  { country: "Tunisia", countryCode: "TN", code: "+216" },
  { country: "Turkey", countryCode: "TR", code: "+90" },
  { country: "Turkmenistan", countryCode: "TM", code: "+993" },
  { country: "Tuvalu", countryCode: "TV", code: "+688" },
  { country: "Uganda", countryCode: "UG", code: "+256" },
  { country: "Ukraine", countryCode: "UA", code: "+380" },
  { country: "United Arab Emirates", countryCode: "AE", code: "+971" },
  { country: "United Kingdom", countryCode: "GB", code: "+44" },
  { country: "United States", countryCode: "US", code: "+1" },
  { country: "Uruguay", countryCode: "UY", code: "+598" },
  { country: "Uzbekistan", countryCode: "UZ", code: "+998" },
  { country: "Vanuatu", countryCode: "VU", code: "+678" },
  { country: "Vatican City", countryCode: "VA", code: "+379" },
  { country: "Venezuela", countryCode: "VE", code: "+58" },
  { country: "Vietnam", countryCode: "VN", code: "+84" },
  { country: "Yemen", countryCode: "YE", code: "+967" },
  { country: "Zambia", countryCode: "ZM", code: "+260" },
  { country: "Zimbabwe", countryCode: "ZW", code: "+263" }
];

